orchard_crm/apps/home/urls.py
from django.conf.urls import url
from home.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(HomeDashboard.as_view()), name='home-dashboard'),
]

orchard_crm/apps/lead/urls.py
from django.conf.urls import url, include
from django.views.generic import View
from lead.views import *

urlpatterns = [
    url(r'^$', LeadListView.as_view(), name='lead-list'),
    url(r'^create$', LeadCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', LeadUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', LeadDeleteView.as_view(), name='delete'),
]

orchard_crm/apps/users/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from users.views import *

urlpatterns = [
    url(r'^logout', log_out, name="logout"),
    url(r'^profile', profile, name="profile"),
    url(r'^profile/(?P<pk>\d+)/$', UpdateUserProfileView.as_view(), name="update-profile"),
    url(r'^activate/(?P<pk>\d+)/$', activate, name="activate"),
    url(r'^create/$', create_user, name="create_user"),
    url(r'^request_password_reset/$', request_password_reset, name="request_password_reset"),
    url(r'^reset_password/(?P<pk>\d+)/$',reset_password, name="reset_password"),
    url(r'^login/$', login, name="login"),
    url(r'^changepassword/$', changepassword, name="changepassword"),
]

orchard_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^user/', include('users.urls',namespace='user')),
    url(r'^campaign/', include('campaign.urls',namespace='campaign')),
    url(r'^prospect/', include('prospect.urls',namespace='prospect')),
    url(r'^appointment/', include('appointment.urls',namespace='appointment')),
    url(r'^lead/', include('lead.urls',namespace='lead')),
	url(r'^contact/', include('contact.urls',namespace='contact')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls',namespace='home')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orchard_crm/apps/appointment/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.conf import settings
from prospect.models import *
from lead.models import *
from contact.models import *
from django.core.urlresolvers import reverse, reverse_lazy
# Create your models here.

class Appointment(AbstractCommon, models.Model):
    """
    Description: Model Description
    """
    appointment_datetime = models.DateTimeField(null=True)
    agency_calling_for = models.TextField(null=True)
    agent = models.ForeignKey(Contact, null=True, related_name='appointment_agent')
    appointment_type = models.TextField(null=True)
    appointment_status = models.TextField(null=True)
    appointment_comment = models.TextField(null=True)
    lead = models.ForeignKey(Lead, null=True, related_name='appointment_lead')
    def __unicode__(self):
        return self.agent
    def get_absolute_url(self):
        return reverse("appointment:appointment-list")

orchard_crm/apps/contact/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.conf import settings
from prospect.models import *
from contact.models import *
# Create your models here.

class Contact(AbstractCommon, models.Model):
    """
    Description: Model Description
    """
    email = models.EmailField(max_length=255)
    additional_email = models.EmailField(max_length=255)
    password = models.CharField(max_length=50)
    log_in_type = models.CharField(max_length=255)
    account_name = models.CharField(max_length=255)
    agency_name = models.CharField(max_length=255)
    notes = models.CharField(max_length=255)
    plan_purchased = models.CharField(max_length=255)
    number_of_appointment = models.IntegerField()
    is_client_Active = models.BooleanField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, unique=False, related_name='contact_created_by', on_delete=models.CASCADE)

orchard_crm/apps/home/models.py
from django.db import models

# Create your models here.

orchard_crm/apps/appointment/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from appointment.models import Appointment
class AppointmentCreateForm(forms.ModelForm):
  class Meta:
    model = Appointment
    exclude = ('title', 'county', 'agent','lead',)
    widgets = {
          'first_name': forms.TextInput(attrs={'type':'first_name', 'class':'form-control'}),
          'last_name': forms.TextInput(attrs={'type':'last_name', 'class':'form-control'}),
          'phone_number': forms.TextInput(attrs={'type':'phone_number', 'class':'form-control'}),
          'company_name': forms.TextInput(attrs={'type':'company_name', 'class':'form-control'}),
          'address': forms.TextInput(attrs={'type':'address', 'class':'form-control'}),
          'city': forms.TextInput(attrs={'type':'location_city', 'class':'form-control'}),
          'state': forms.TextInput(attrs={'type':'location_state', 'class':'form-control'}),
          'zip_code': forms.TextInput(attrs={'type':'location_zip_code', 'class':'form-control'}),
          'agency_calling_for': forms.TextInput(attrs={'type':'agency_calling_for', 'class':'form-control'}),
          'appointment_datetime': forms.DateInput(attrs={'type':'appointment_datetime', 'class':'timePicker'}),
          'appointment_type': forms.TextInput(attrs={'type':'appointment_type', 'class':'form-control'}),
          'appointment_status': forms.TextInput(attrs={'type':'appointment_status', 'class':'form-control'}),
          'appointment_comment': forms.TextInput(attrs={'type':'appointment_comment', 'class':'form-control'}),
    }

orchard_crm/apps/campaign/forms.py
from django import forms

from .models import *

class CreateCampaignForm(forms.ModelForm):

    # title = forms.CharField(max_length=100, min_length=20)

    class Meta:
        model = Campaign
        exclude = ('twilio_cid','created_by', 'prospect','location_geocoords',)

    def __init__(self, *args, **kwargs):
        super(CreateCampaignForm, self).__init__(*args, **kwargs)

        for fields in self.fields:
        	self.fields[fields].widget = forms.TextInput(attrs={
            'class': 'form-control'})

orchard_crm/apps/lead/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from .models import Lead
class LeadCreateForm(forms.ModelForm):
  class Meta:
    model = Lead
    exclude = ('lead_created','lead_modified','lead_category_modified','agent',)
    
    def __init__(self, *args, **kwargs):
      super(LeadCreateForm, self).__init__(*args, **kwargs)
    widgets = {
          'appointment_datetime': forms.DateInput(attrs={'type':'appointment_datetime', 'class':'timePicker'}),
          'company_name': forms.TextInput(attrs={'type':'company_name', 'class':'form-control'}),
          'title': forms.TextInput(attrs={'type':'title', 'class':'form-control'}),
          'first_name': forms.TextInput(attrs={'type':'first_name', 'class':'form-control'}),
          'last_name': forms.TextInput(attrs={'type':'last_name', 'class':'form-control'}),
          'phone_number': forms.TextInput(attrs={'type':'phone_number', 'class':'form-control'}),
          'alternative_phone_number': forms.TextInput(attrs={'type':'alternative_phone_number', 'class':'form-control'}),
          'email_address': forms.EmailInput(attrs={'type':'email_address', 'class':'form-control'}),
          'company_website': forms. URLInput(attrs={'type':'company_website', 'class':'form-control'}),
          'years_in_business': forms.TextInput(attrs={'type':'years_in_business', 'class':'form-control'}),
          'agency_calling_for': forms.TextInput(attrs={'type':'agency_calling_for', 'class':'form-control'}),
          'appointment_type': forms.TextInput(attrs={'type':'appointment_type', 'class':'form-control'}),
          'address': forms.TextInput(attrs={'type':'address', 'class':'form-control'}),
          'city': forms.TextInput(attrs={'type':'location_city', 'class':'form-control'}),
          'state': forms.TextInput(attrs={'type':'location_state', 'class':'form-control'}),
          'zip_code': forms.TextInput(attrs={'type':'location_zip_code', 'class':'form-control'}),
          'county': forms.TextInput(attrs={'type':'county', 'class':'form-control'}),
          'location_latitude_longitude': forms.TextInput(attrs={'type':'location_latitude_longitude', 'class':'form-control'}),
          'sic_code': forms.TextInput(attrs={'type':'sic_code', 'class':'form-control'}),
          'sic_code_description': forms.TextInput(attrs={'type':'sic_code_description', 'class':'form-control'}),
          'naics_code': forms.TextInput(attrs={'type':'naics_code', 'class':'form-control'}),
          'naics_code_description': forms.TextInput(attrs={'type':'naics_code_description', 'class':'form-control'}),
          'lead_category': forms.TextInput(attrs={'type':'lead_category', 'class':'form-control'}),
          'lead_created_by': forms.TextInput(attrs={'type':'lead_created_by', 'class':'form-control'}),
          'lead_modified_by': forms.TextInput(attrs={'type':'lead_modified_by', 'class':'form-control'}),
          'lead_category_modified_by': forms.TextInput(attrs={'type':'lead_category_modified_by', 'class':'form-control'}),
          'next_renewal_date': forms.DateInput(attrs={'type':'next_renewal_date', 'class':'datepicker'}),
          'liability_carrier': forms.TextInput(attrs={'type':'liability_carrier', 'class':'form-control'}),
          'liability_renewal_date': forms.DateInput(attrs={'type':'liability_renewal_date', 'class':'datepicker'}),
          'total_locations': forms.TextInput(attrs={'type':'total_locations', 'class':'form-control'}),
          'workers_compensation_renewal_date': forms.DateInput(attrs={'type':'workers_compensation_renewal_date', 'class':'datepicker'}),
          'workers_compensation_carrier': forms.TextInput(attrs={'type':'workers_compensation_carrier', 'class':'form-control'}),
          'total_employees': forms.TextInput(attrs={'type':'total_employees', 'class':'form-control'}),
          'auto_renewal_date': forms.DateInput(attrs={'type':'auto_renewal_date', 'class':'datepicker'}),
          'auto_carrier': forms.TextInput(attrs={'type':'auto_carrier', 'class':'form-control'}),
          'lead_comments': forms.TextInput(attrs={'type':'lead_comments', 'class':'form-control'}),
          'user_notes': forms.TextInput(attrs={'type':'user_notes', 'class':'form-control'}),
          'return_for_credit_request': forms.TextInput(attrs={'type':'return_for_credit_request', 'class':'form-control'}),
    }

    # def __init__(self, *args, **kwargs):
    #     super(LeadCreateForm, self).__init__(*args, **kwargs)

    #     for fields in self.fields:
    #       self.fields[fields].widget = forms.TextInput(attrs={
    #         'class': 'form-control'})

orchard_crm/apps/appointment/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from appointment.models import Appointment
from .forms import *
from lead.forms import *
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, Http404, HttpResponse 


class AppointmentListView(ListView):
    """docstring for AppointmentListView"""
    model = Appointment
    template_name = 'appointment/appointment_list.html'
    context_object_name = 'appointment_list'
    paginate_by = 10



def create(request):
      if request.method == 'POST':
            form = AppointmentCreateForm(data=request.POST)
            if form.is_valid():
                form_obj = form.save(commit=False)
                lead = Lead.objects.create(
                  first_name=form_obj.first_name, last_name=form_obj.last_name, company_name=form_obj.company_name,
                  phone_number=form_obj.phone_number, address=form_obj.address, city=form_obj.city,state=form_obj.state,
                  zip_code=form_obj.zip_code, appointment_datetime=form_obj.appointment_datetime, agency_calling_for=form_obj.agency_calling_for,
                  appointment_type=form_obj.appointment_type, lead_comments=form_obj.appointment_comment,
                  )
                lead.save()
                form_obj.lead_id = lead.id 
                form_obj.save()
                return HttpResponseRedirect(reverse("appointment:appointment-list"))
      else:
        return render(request, 'appointment/create_appointment.html', {'form':AppointmentCreateForm})
     

class AppointmentCreateView(CreateView):
      model = Appointment
      form = AppointmentCreateForm
      template_name = 'appointment/create_appointment.html'

orchard_crm/apps/campaign/views.py
from django.shortcuts import render
from django.views.generic import ListView, UpdateView
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect, Http404, HttpResponse
from .models import *
from .forms import *
from prospect.models import *
from django.core.urlresolvers import reverse

# Create your views here.
class CampaignListView(ListView):
    """docstring for CampaignListView"""
    model = Campaign
    template_name = 'campaign/campaign_list.html'
    context_object_name = 'campagns'
        
class CampaignCreate(CreateView):
    model = Campaign
    form_class = CreateCampaignForm
    template_name = 'campaign/create_campaign.html'
    # success_url = reverse("campaign:campaign-list")

    def get(self, request, **kwargs):
        context = {}
        if request.user.is_authenticated() and request.user.is_superuser:
            prospect_obj = Prospect.objects.all().values()[:1]
            prospects_fields = []

        for po in prospect_obj:
            for k,v in po.items():
                prospects_fields.append(k)
        context['prospects_fields'] = prospects_fields

        return render(request, self.template_name, {'context':context })

    def post(self, request, **kwargs):
        form = self.form_class(request.POST)
        self.form_valid(form)
        return HttpResponseRedirect(reverse("campaign:campaign-list"))

    def form_valid(self, form):
        if form.is_valid():
            form.instance.created_by = self.request.user
            form.save()
            return super(CampaignCreate, self).form_valid(form)
        else:
            return render(request, self.template_name, {'form':form })
            

class CampaignUpdate(UpdateView):
    model = Campaign
    form_class = CreateCampaignForm
    template_name = 'campaign/create_campaign.html'

    def get_object(self):
        return self.model.objects.get(pk=self.kwargs['pk'])

orchard_crm/apps/contact/views.py
from django.shortcuts import render
from django.views.generic import ListView


# Create your views here.
class ContactListView(ListView):
	"""docstring for ContactListView"""
	def __init__(self, arg):
		super(ContactListView, self).__init__()
		self.arg = arg
		

orchard_crm/apps/home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from users.models import *
from django.core.cache import cache 
import datetime
from django.conf import settings
from django.core.cache import cache
from django.conf import settings

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
class HomeDashboard(ListView):
    """docstring for HomeDashboard"""
    template_name = 'home/dashbord.html'
    model = CustomUser
    context_object_name = 'users'

    

orchard_crm/apps/lead/views.py
from django.shortcuts import render, render_to_response, get_list_or_404, get_object_or_404
from django.views.generic import ListView, UpdateView, DetailView, DeleteView
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect, Http404, HttpResponse
from .models import *
from .forms import *
from django.core.urlresolvers import reverse, reverse_lazy 


class LeadListView(ListView):
    """docstring for LeadListView"""
    model = Lead
    template_name = 'lead/lead_list.html'
    context_object_name = 'lead_list'
    paginate_by = 10

class LeadCreateView(CreateView):
    model = Lead
    form_class = LeadCreateForm
    template_name = 'lead/create_lead.html'
    def create(request):
        if request.method == 'POST':
            form = form_class(data=request.POST, files=request.FILES)
            if form.is_valid():
                # form.instance.created_by = self.request.user

                form.save()
                return HttpResponseRedirect(reverse("lead:lead-list"))
        else:
            return render(request, self.template_name, {'form':LeadCreateForm})            



class LeadUpdateView(UpdateView):
    model = Lead
    form_class = LeadCreateForm
    template_name = 'lead/lead_update.html'
# import pdb; pdb.set_trace()
class LeadDeleteView(DeleteView):
    template_name = 'lead/lead_delete.html'
    model = Lead
    success_url = reverse_lazy('lead:lead-list')

orchard_crm/apps/prospect/views.py
from django.shortcuts import render
from django.views.generic import ListView


# Create your views here.
class ProspectListView(ListView):
	"""docstring for ProspectListView"""
	def __init__(self, arg):
		super(ProspectListView, self).__init__()
		self.arg = arg
		

orchard_crm/templates/lead/create_lead.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load i18n %}
  
{% block title %}
  {% trans 'OrchardCRM | Create Lead' %}
{% endblock %}


{% block content %}
      <div class="container">
            <div class="row">
              <div id="boxmap"></div>
              <div id="map_results_county" style="word-wrap: break-word;"><span id="county_cnt">0</span> counties found&nbsp;<span id="county_list"></span></div>
                <div class="col-md-4 col-md-offset-4">
                        <form id="lead-create-form" action="/lead/create" method="post" enctype="multipart/form-data">
                              {% csrf_token %}
                              {% for field in form %}
                                    <div class="row">
                                          <div class="form-group">
                                            <div class="col-md-6">
                                              {{ field.label_tag }}
                                            </div>
                                            <div class="col-md-6">
                                              {{ field }}
                                            </div>
                                          </div>
                                    </div>
                              {% endfor %}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                  </div>
            </div>
      </div>  
      <div id='map-one' class='map'> </div>
{% endblock %}

orchard_crm/templates/lead/lead_delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %}{{object_name}} Confirm delete?{% endblock %}
{% block content %}
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Lead Delete Form</h4>
      </div>
      <div class="modal-body">
            <div id="content-container" class="container p-none">
                  <div class="side-p">
                      <h3>Are you sure?</h3>
                      <p>You're about to delete {{ object }}. Please confirm.</p>
                        <form action="{% url 'lead:delete' lead.id %}" method="post">
                          {% csrf_token %}
                          <input class="btn btn-link" 
                                 type="button" value="Cancel" 
                                 onclick="window.history.go(-1);"/>
                          <input class="btn btn-danger" type="submit" value="Confirm"/>
                        </form>
                  </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
{% endblock %}

orchard_crm/templates/lead/lead_list.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load i18n %}
  
{% block title %}
  {% trans 'OrchardCRM | Lead List' %}
{% endblock %}

{% block style %}
  
{% endblock %}

{% block content %}
      <div class="container">
            <div class="row">
              <div id="boxmap"></div>
              <div id="map_results_county" style="word-wrap: break-word;"><span id="county_cnt">0</span> counties found&nbsp;<span id="county_list"></span></div>
                  {% if lead_list %}
                        <table id="myTable" class="table  table-bordered ">
                              <thead>
                                  <tr>
                                    <th>Appointment Datetime</th>
                                    <th>Company Name </th>
                                    <th>Title </th>
                                    <th>First Name </th>
                                    <th>Last Name </th>
                                    <th>Phone Number </th>
                                    <th>Alternative Phone Number </th>
                                    <th>Email Address </th>
                                    <th>Company Website </th>
                                    <th>Years In Business </th>
                                    <th>Agency Calling For </th>
                                    <th>Agent </th>
                                    <th>Appointment Type </th>
                                    <th>Verified </th>
                                    <th>Address </th>
                                    <th>Location City </th>
                                    <th>Location State </th>
                                    <th>Location Zip Code </th>
                                    <th>County </th>
                                    <th>Location Latitude Longitude </th>
                                    <th>SIC Code </th>
                                    <th>SIC Code Description </th>
                                    <th>NAICS Code </th>
                                    <th>NAICS Code Description </th>
                                    <th>Lead Category </th>
                                    <th>Lead Created By </th> 
                                    <th>Lead Created </th> 
                                    <th>Lead Modified By </th> 
                                    <th>Lead Modified </th> 
                                    <th>Lead Category Modified By </th> 
                                    <th>Lead Category Modified </th> 
                                    <th>Next Renewal Date </th>
                                    <th>Liability Carrier </th> 
                                    <th>Liability Renewal Date </th>
                                    <th>Total Locations </th> 
                                    <th>Workers Compensation Renewal Date </th>
                                    <th>Workers Compensation Carrier </th> 
                                    <th>TotaL Employees </th> 
                                    <th>Auto Renewal Date </th>
                                    <th>Auto Carrier </th>
                                    <th>TotaL Vehicles </th> 
                                    <th>Lead Comments </th>
                                    <th>User Notes </th> 
                                    <th>Attachments </th> 
                                    <th>Return For Credit Request </th>
                                    <th></th>
                                    <th></th>
                                  </tr>
                              </thead>
                              {% for lead in lead_list %}
                                    <tbody>
                                      <tr>
                                        <td>{{lead.appointment_datetime}}</td>
                                        <td>{{lead.company_name}}</td>
                                        <td>{{lead.title}}</td>
                                        <td>{{lead.first_name}}</td>
                                        <td>{{lead.last_name}}</td>
                                        <td>{{lead.phone_number}}</td>
                                        <td>{{lead.alternative_phone_number}}</td>
                                        <td>{{lead.email_address}}</td>
                                        <td>{{lead.company_website}}</td>
                                        <td>{{lead.years_in_business}}</td>
                                        <td>{{lead.agency_calling_for}}</td>
                                        <td>{{lead.agent}}</td>
                                        <td>{{lead.appointment_type}}</td>
                                        <td>{{lead.verified}}</td>
                                        <td>{{lead.address}}</td>
                                        <td>{{lead.city}}</td>
                                        <td>{{lead.state}}</td>
                                        <td>{{lead.zip_code}}</td>
                                        <td>{{lead.county}}</td>
                                        <td>{{lead.location_latitude_longitude}}</td>
                                        <td>{{lead.sic_code}}</td>
                                        <td>{{lead.sic_code_description}}</td>
                                        <td>{{lead.naics_code}}</td>
                                        <td>{{lead.naics_code_description}}</td>
                                        <td>{{lead.lead_category}}</td>
                                        <td>{{lead.lead_created_by}}</td>
                                        <td>{{lead.lead_created}}</td>
                                        <td>{{lead.lead_modified_by}}</td>
                                        <td>{{lead.lead_modified}}</td>
                                        <td>{{lead.lead_category_modified_by}}</td>
                                        <td>{{lead.lead_category_modified}}</td>
                                        <td>{{lead.next_renewal_date}}</td>
                                        <td>{{lead.liability_carrier}}</td>
                                        <td>{{lead.liability_renewal_date}}</td>
                                        <td>{{lead.total_locations}}</td>
                                        <td>{{lead.workers_compensation_renewal_date}}</td>
                                        <td>{{lead.workers_compensation_carrier}}</td>
                                        <td>{{lead.total_employees}}</td>
                                        <td>{{lead.auto_renewal_date}}</td>
                                        <td>{{lead.auto_carrier}}</td>
                                        <td>{{lead.total_vehicles}}</td>
                                        <td>{{lead.lead_comments}}</td>
                                        <td>{{lead.user_notes}}</td>
                                        <td>{{lead.attachments}}</td>
                                        <td>{{lead.return_for_credit_request}}</td>
                                        <td><a href="{% url 'lead:update' lead.id %}" data-toggle="modal" data-target="#myModal" class="glyphicon glyphicon-edit"></a></td>
                                        <td><a href="{% url 'lead:delete' lead.id %}" data-toggle="modal" data-target="#myModal" class="glyphicon glyphicon-trash"></a></td>
                                      </tr>
                                    </tbody>
                              {% endfor %}
                        </table>
                      {# .... **Now the pagination section** .... #}
                      {% if is_paginated %}
                          <div class="pagination">
                              <span class="page-links">
                                  {% if page_obj.has_previous %}
                                      <a href="/leads?page={{ page_obj.previous_page_number }}">previous</a>
                                  {% endif %}
                                  <span class="page-current">
                                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                  </span>
                                  {% if page_obj.has_next %}
                                      <a href="/leads?page={{ page_obj.next_page_number }}">next</a>
                                  {% endif %}
                              </span>
                          </div>
                      {% endif %}
                  {% else %}
                      <h3>My leads</h3>
                      <p>No leads found!!! :(</p>
                  {% endif %}
            </div>
      </div>
      <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
              <!-- Modal content-->
              <div class="modal-content">
                    
              </div>
            </div>
      </div>  
  <div id='map-one' class='map'> </div>
{% endblock %}

orchard_crm/templates/lead/lead_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block stylesheet %}
     <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Lead Update Form</h4>
      </div>
      <div class="modal-body">
            <form action="{% url 'lead:update' lead.id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Update" />
            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker_timepicker.min.js' %}"></script>
    <script src="{% static 'js/date_time.js' %}"></script>
{% endblock %}

orchard_crm/templates/lead/search.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load i18n %}
  
{% block title %}
  {% trans 'OrchardCRM | Profile' %}
{% endblock %}


{% block content %}

{% endblock %}

{% block script %}


{% endblock %}