orchard_crm/apps/appointment/urls.py
from django.conf.urls import url
from appointment.views import *

urlpatterns = [
    url(r'^$', AppointmentListView.as_view(), name='appointment-list'),
    url(r'^create$', create, name='create-appointment'),
]

orchard_crm/apps/campaign/urls.py
from django.conf.urls import url
from campaign.views import *

urlpatterns = [
    url(r'^$', CampaignListView.as_view(), name='campaign-list'),
    url(r'^create/$', CampaignCreate.as_view(), name='campaign-create'),
    url(r'^edit/(?P<pk>\d+)/$', CampaignUpdate.as_view(), name='campaign-update'),
]

orchard_crm/apps/home/urls.py
from django.conf.urls import url
from home.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(HomeDashboard.as_view()), name='home-dashboard'),
]

orchard_crm/apps/lead/urls.py
from django.conf.urls import url, include
from django.views.generic import View
from lead.views import *

urlpatterns = [
    url(r'^$', LeadListView.as_view(), name='lead-list'),
    url(r'^create$', LeadCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', LeadUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', LeadDeleteView.as_view(), name='delete'),
]

orchard_crm/apps/users/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from users.views import *

urlpatterns = [
    url(r'^logout', log_out, name="logout"),
    url(r'^profile', profile, name="profile"),
    url(r'^profile/(?P<pk>\d+)/$', UpdateUserProfileView.as_view(), name="update-profile"),
    url(r'^activate/(?P<pk>\d+)/$', activate, name="activate"),
    url(r'^create/$', create_user, name="create_user"),
    url(r'^request_password_reset/$', request_password_reset, name="request_password_reset"),
    url(r'^reset_password/(?P<pk>\d+)/$',reset_password, name="reset_password"),
    url(r'^login/$', login, name="login"),
    url(r'^changepassword/$', changepassword, name="changepassword"),
]

orchard_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^user/', include('users.urls',namespace='user')),
    url(r'^campaign/', include('campaign.urls',namespace='campaign')),
    url(r'^prospect/', include('prospect.urls',namespace='prospect')),
    url(r'^appointment/', include('appointment.urls',namespace='appointment')),
    url(r'^lead/', include('lead.urls',namespace='lead')),
	url(r'^contact/', include('contact.urls',namespace='contact')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls',namespace='home')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orchard_crm/apps/appointment/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.conf import settings
from prospect.models import *
from lead.models import *
from contact.models import *
from django.core.urlresolvers import reverse, reverse_lazy
# Create your models here.

class Appointment(AbstractCommon, models.Model):
    """
    Description: Model Description
    """
    appointment_datetime = models.DateTimeField(null=True)
    agency_calling_for = models.TextField(null=True)
    agent = models.ForeignKey(Contact, null=True, related_name='appointment_agent')
    appointment_type = models.TextField(null=True)
    appointment_status = models.TextField(null=True)
    appointment_comment = models.TextField(null=True)
    lead = models.ForeignKey(Lead, null=True, related_name='appointment_lead')
    def __unicode__(self):
        return self.agent
    def get_absolute_url(self):
        return reverse("appointment:appointment-list")

orchard_crm/apps/home/models.py
from django.db import models

# Create your models here.

orchard_crm/apps/appointment/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from appointment.models import Appointment
class AppointmentCreateForm(forms.ModelForm):
  class Meta:
    model = Appointment
    exclude = ('title', 'county', 'agent','lead',)
    widgets = {
          'first_name': forms.TextInput(attrs={'type':'first_name', 'class':'form-control'}),
          'last_name': forms.TextInput(attrs={'type':'last_name', 'class':'form-control'}),
          'phone_number': forms.TextInput(attrs={'type':'phone_number', 'class':'form-control'}),
          'company_name': forms.TextInput(attrs={'type':'company_name', 'class':'form-control'}),
          'address': forms.TextInput(attrs={'type':'address', 'class':'form-control'}),
          'city': forms.TextInput(attrs={'type':'location_city', 'class':'form-control'}),
          'state': forms.TextInput(attrs={'type':'location_state', 'class':'form-control'}),
          'zip_code': forms.TextInput(attrs={'type':'location_zip_code', 'class':'form-control'}),
          'agency_calling_for': forms.TextInput(attrs={'type':'agency_calling_for', 'class':'form-control'}),
          'appointment_datetime': forms.DateInput(attrs={'type':'appointment_datetime', 'class':'timePicker'}),
          'appointment_type': forms.TextInput(attrs={'type':'appointment_type', 'class':'form-control'}),
          'appointment_status': forms.TextInput(attrs={'type':'appointment_status', 'class':'form-control'}),
          'appointment_comment': forms.TextInput(attrs={'type':'appointment_comment', 'class':'form-control'}),
    }

orchard_crm/apps/campaign/forms.py
from django import forms

from .models import *

class CreateCampaignForm(forms.ModelForm):

    # title = forms.CharField(max_length=100, min_length=20)

    class Meta:
        model = Campaign
        exclude = ('twilio_cid','created_by', 'prospect','location_geocoords',)

    def __init__(self, *args, **kwargs):
        super(CreateCampaignForm, self).__init__(*args, **kwargs)

        for fields in self.fields:
        	self.fields[fields].widget = forms.TextInput(attrs={
            'class': 'form-control'})

orchard_crm/apps/lead/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from .models import Lead
class LeadCreateForm(forms.ModelForm):
  class Meta:
    model = Lead
    exclude = ('lead_created','lead_modified','lead_category_modified','agent',)
    
    def __init__(self, *args, **kwargs):
      super(LeadCreateForm, self).__init__(*args, **kwargs)
    widgets = {
          'appointment_datetime': forms.DateInput(attrs={'type':'appointment_datetime', 'class':'timePicker'}),
          'company_name': forms.TextInput(attrs={'type':'company_name', 'class':'form-control'}),
          'title': forms.TextInput(attrs={'type':'title', 'class':'form-control'}),
          'first_name': forms.TextInput(attrs={'type':'first_name', 'class':'form-control'}),
          'last_name': forms.TextInput(attrs={'type':'last_name', 'class':'form-control'}),
          'phone_number': forms.TextInput(attrs={'type':'phone_number', 'class':'form-control'}),
          'alternative_phone_number': forms.TextInput(attrs={'type':'alternative_phone_number', 'class':'form-control'}),
          'email_address': forms.EmailInput(attrs={'type':'email_address', 'class':'form-control'}),
          'company_website': forms. URLInput(attrs={'type':'company_website', 'class':'form-control'}),
          'years_in_business': forms.TextInput(attrs={'type':'years_in_business', 'class':'form-control'}),
          'agency_calling_for': forms.TextInput(attrs={'type':'agency_calling_for', 'class':'form-control'}),
          'appointment_type': forms.TextInput(attrs={'type':'appointment_type', 'class':'form-control'}),
          'address': forms.TextInput(attrs={'type':'address', 'class':'form-control'}),
          'city': forms.TextInput(attrs={'type':'location_city', 'class':'form-control'}),
          'state': forms.TextInput(attrs={'type':'location_state', 'class':'form-control'}),
          'zip_code': forms.TextInput(attrs={'type':'location_zip_code', 'class':'form-control'}),
          'county': forms.TextInput(attrs={'type':'county', 'class':'form-control'}),
          'location_latitude_longitude': forms.TextInput(attrs={'type':'location_latitude_longitude', 'class':'form-control'}),
          'sic_code': forms.TextInput(attrs={'type':'sic_code', 'class':'form-control'}),
          'sic_code_description': forms.TextInput(attrs={'type':'sic_code_description', 'class':'form-control'}),
          'naics_code': forms.TextInput(attrs={'type':'naics_code', 'class':'form-control'}),
          'naics_code_description': forms.TextInput(attrs={'type':'naics_code_description', 'class':'form-control'}),
          'lead_category': forms.TextInput(attrs={'type':'lead_category', 'class':'form-control'}),
          'lead_created_by': forms.TextInput(attrs={'type':'lead_created_by', 'class':'form-control'}),
          'lead_modified_by': forms.TextInput(attrs={'type':'lead_modified_by', 'class':'form-control'}),
          'lead_category_modified_by': forms.TextInput(attrs={'type':'lead_category_modified_by', 'class':'form-control'}),
          'next_renewal_date': forms.DateInput(attrs={'type':'next_renewal_date', 'class':'datepicker'}),
          'liability_carrier': forms.TextInput(attrs={'type':'liability_carrier', 'class':'form-control'}),
          'liability_renewal_date': forms.DateInput(attrs={'type':'liability_renewal_date', 'class':'datepicker'}),
          'total_locations': forms.TextInput(attrs={'type':'total_locations', 'class':'form-control'}),
          'workers_compensation_renewal_date': forms.DateInput(attrs={'type':'workers_compensation_renewal_date', 'class':'datepicker'}),
          'workers_compensation_carrier': forms.TextInput(attrs={'type':'workers_compensation_carrier', 'class':'form-control'}),
          'total_employees': forms.TextInput(attrs={'type':'total_employees', 'class':'form-control'}),
          'auto_renewal_date': forms.DateInput(attrs={'type':'auto_renewal_date', 'class':'datepicker'}),
          'auto_carrier': forms.TextInput(attrs={'type':'auto_carrier', 'class':'form-control'}),
          'lead_comments': forms.TextInput(attrs={'type':'lead_comments', 'class':'form-control'}),
          'user_notes': forms.TextInput(attrs={'type':'user_notes', 'class':'form-control'}),
          'return_for_credit_request': forms.TextInput(attrs={'type':'return_for_credit_request', 'class':'form-control'}),
    }

    # def __init__(self, *args, **kwargs):
    #     super(LeadCreateForm, self).__init__(*args, **kwargs)

    #     for fields in self.fields:
    #       self.fields[fields].widget = forms.TextInput(attrs={
    #         'class': 'form-control'})

orchard_crm/apps/appointment/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from appointment.models import Appointment
from .forms import *
from lead.forms import *
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, Http404, HttpResponse 


class AppointmentListView(ListView):
    """docstring for AppointmentListView"""
    model = Appointment
    template_name = 'appointment/appointment_list.html'
    context_object_name = 'appointment_list'
    paginate_by = 10



def create(request):
      if request.method == 'POST':
            form = AppointmentCreateForm(data=request.POST)
            if form.is_valid():
                form_obj = form.save(commit=False)
                lead = Lead.objects.create(
                  first_name=form_obj.first_name, last_name=form_obj.last_name, company_name=form_obj.company_name,
                  phone_number=form_obj.phone_number, address=form_obj.address, city=form_obj.city,state=form_obj.state,
                  zip_code=form_obj.zip_code, appointment_datetime=form_obj.appointment_datetime, agency_calling_for=form_obj.agency_calling_for,
                  appointment_type=form_obj.appointment_type, lead_comments=form_obj.appointment_comment,
                  )
                lead.save()
                form_obj.lead_id = lead.id 
                form_obj.save()
                return HttpResponseRedirect(reverse("appointment:appointment-list"))
      else:
        return render(request, 'appointment/create_appointment.html', {'form':AppointmentCreateForm})
     

class AppointmentCreateView(CreateView):
      model = Appointment
      form = AppointmentCreateForm
      template_name = 'appointment/create_appointment.html'

orchard_crm/apps/campaign/views.py
from django.shortcuts import render
from django.views.generic import ListView, UpdateView
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect, Http404, HttpResponse
from .models import *
from .forms import *
from prospect.models import *
from django.core.urlresolvers import reverse

# Create your views here.
class CampaignListView(ListView):
    """docstring for CampaignListView"""
    model = Campaign
    template_name = 'campaign/campaign_list.html'
    context_object_name = 'campagns'
        
class CampaignCreate(CreateView):
    model = Campaign
    form_class = CreateCampaignForm
    template_name = 'campaign/create_campaign.html'
    # success_url = reverse("campaign:campaign-list")

    def get(self, request, **kwargs):
        context = {}
        if request.user.is_authenticated() and request.user.is_superuser:
            prospect_obj = Prospect.objects.all().values()[:1]
            prospects_fields = []

        for po in prospect_obj:
            for k,v in po.items():
                prospects_fields.append(k)
        context['prospects_fields'] = prospects_fields

        return render(request, self.template_name, {'context':context })

    def post(self, request, **kwargs):
        form = self.form_class(request.POST)
        self.form_valid(form)
        return HttpResponseRedirect(reverse("campaign:campaign-list"))

    def form_valid(self, form):
        if form.is_valid():
            form.instance.created_by = self.request.user
            form.save()
            return super(CampaignCreate, self).form_valid(form)
        else:
            return render(request, self.template_name, {'form':form })
            

class CampaignUpdate(UpdateView):
    model = Campaign
    form_class = CreateCampaignForm
    template_name = 'campaign/create_campaign.html'

    def get_object(self):
        return self.model.objects.get(pk=self.kwargs['pk'])

orchard_crm/apps/contact/views.py
from django.shortcuts import render
from django.views.generic import ListView


# Create your views here.
class ContactListView(ListView):
	"""docstring for ContactListView"""
	def __init__(self, arg):
		super(ContactListView, self).__init__()
		self.arg = arg
		

orchard_crm/apps/home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from users.models import *
from django.core.cache import cache 
import datetime
from django.conf import settings
from django.core.cache import cache
from django.conf import settings

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
class HomeDashboard(ListView):
    """docstring for HomeDashboard"""
    template_name = 'home/dashbord.html'
    model = CustomUser
    context_object_name = 'users'

    

orchard_crm/apps/lead/views.py
from django.shortcuts import render, render_to_response, get_list_or_404, get_object_or_404
from django.views.generic import ListView, UpdateView, DetailView, DeleteView
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect, Http404, HttpResponse
from .models import *
from .forms import *
from django.core.urlresolvers import reverse, reverse_lazy 


class LeadListView(ListView):
    """docstring for LeadListView"""
    model = Lead
    template_name = 'lead/lead_list.html'
    context_object_name = 'lead_list'
    paginate_by = 10

class LeadCreateView(CreateView):
    model = Lead
    form_class = LeadCreateForm
    template_name = 'lead/create_lead.html'
    def create(request):
        if request.method == 'POST':
            form = form_class(data=request.POST, files=request.FILES)
            if form.is_valid():
                # form.instance.created_by = self.request.user

                form.save()
                return HttpResponseRedirect(reverse("lead:lead-list"))
        else:
            return render(request, self.template_name, {'form':LeadCreateForm})            



class LeadUpdateView(UpdateView):
    model = Lead
    form_class = LeadCreateForm
    template_name = 'lead/lead_update.html'
# import pdb; pdb.set_trace()
class LeadDeleteView(DeleteView):
    template_name = 'lead/lead_delete.html'
    model = Lead
    success_url = reverse_lazy('lead:lead-list')

orchard_crm/apps/prospect/views.py
from django.shortcuts import render
from django.views.generic import ListView


# Create your views here.
class ProspectListView(ListView):
	"""docstring for ProspectListView"""
	def __init__(self, arg):
		super(ProspectListView, self).__init__()
		self.arg = arg
		

orchard_crm/templates/base.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
   		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>
			{% block title %}{% endblock %}
		</title>

		{% block stylesheet %}{% endblock %}
		
		{% block extrastyle %}{% endblock %}
		
		{% block extrahead %}{% endblock %}
		
	</head>
	
	<body>
		<!-- Container -->
		<div id="container">
    			<!-- Header -->
    			
			{% block branding %}{% endblock %}
			<!-- END Header -->
		    {% block breadcrumbs %}
		    {% endblock %}

		    {% block messages %}
		    {% endblock messages %}

		    {% block content %}
		    {% endblock %}



		</div>
		<!-- END Container -->
    {% block footer %}{% endblock %}
	</body>
	{% block script %}
	{% endblock %}
</html>

orchard_crm/templates/layout.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{% endblock %}

{% block stylesheet %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/mapbox.css' %}" rel="stylesheet">
    <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.css' rel='stylesheet' />
    <link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.3/leaflet.draw.css' rel='stylesheet' />
    <link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
    <link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-editable.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"/>
{% endblock %}


{% block branding %}
	<div class="row border-bottom">
        <div class="row border-bottom white-bg">
          <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-header">
              <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <i class="fa fa-reorder"></i>
              </button>
              <a href="#" class="navbar-brand">Lead Orchard</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">
              <ul class="nav navbar-nav top-header">
                <li class="{% ifequal request.path '/home' %} active {% endifequal %}">
                    <a href="{% url 'home:home-dashboard' %}">Home</a>
                </li>
                <li class="{% if '/campaign' in request.path and not '/reports/campaign_reports' in request.path %} active {% endif %}">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">Campaign&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'campaign:campaign-create' %}">New Campaign</a></li>
                        <li><a href="{% url 'campaign:campaign-list' %}">List Campaigns</a></li>
                    </ul>
                </li>

                <li class="{% if '/leads' in request.path %} active {% endif %} dropdown ">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">Leads&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="/lead/search">Search</a></li>
                      <li><a href="{% url 'lead:create' %}">New Lead</a></li>
                      <li><a href="{% url 'lead:lead-list' %}">Lead List</a></li>
                    </ul>
                </li>
                <li class="{% if '/appointments' in request.path %} active {% endif %}">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">Appointments&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="/appointments">Search</a></li>
                      <li><a href="{% url 'appointment:create-appointment' %}">New Appointment</a></li>
                      <li><a href="{% url 'appointment:appointment-list' %}">Appointment List</a></li>
                      <li><a href="/appointments/calendar">Calendar</a></li>
                    </ul>
                </li>
                <li class="{% if '/callbacks' in request.path %} active {% endif %}">
                    <a href="/callbacks">Call Back</a>
                </li>
                
                <li class="{% if '/reports/user_reports' in request.path or '/reports/campaign_reports' in request.path and '/reports/calls' not in request.path %} active {% endif %} dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">Reports&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="/reports/user_reports">User Reports</a></li>
                      <li class="{% if '/reports/calls' in request.path %} active {% endif %}">
                        <a href="/reports/calls">Call History Reports</a>
                      </li>
                      {% if request.user.is_superuser %}
                        <li><a href="/reports/campaign_reports">Campaign Reports</a></li>
                      {% endif %}
                    </ul>
                </li>
                {% if request.user.is_superuser %}
                  <li class="{% if '/prospects' in request.path %} active {% endif %}">
                      <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">Prospects&nbsp;<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        {# <li><a href="{% url 'campaign:campaign-create' %}">New Campaign</a></li> #}
                        {# <li><a href="{% url 'campaign:campaign-update' 3 %}">Edit Campaigns</a></li> #}
                        <li><a href="/prospects/add">Upload Prospects</a></li>
                        <li><a href="/prospects/entry_search">Search Prospects</a></li>
                        
                      </ul>
                  </li>
                  <li class="{% if '/contacts' in request.path %} active {% endif %} dropdown">
                      <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">Contacts&nbsp;<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="/contacts/view_all">View All Contacts</a></li>
                        <!-- <li><a href="/contacts/add_entry">Add Contact Entry</a></li>
                        <li><a href="/contacts/entry_search">Search/Edit Contact Entry</a></li> -->
                        <li><a href="/contacts/add_sql">Upload Contact Collection</a></li>
                      </ul>
                  </li>
                {% endif %}
                <li><a href="javascript:;" class="btn btn-sm btn-primary btn-dialpad"><i class="fa fa-phone"></i></a></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <!--<li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>-->
                        <li>
                            <a href="{% url 'user:profile' %}">Settings</a>
                        </li>
                        {% if request.user.is_superuser %}
                          <li>
                              <a href="{% url 'user:create_user' %}">Create User</a>
                          </li>
                        {% endif %}
                        <li>
                          <a href="/table_display">Table Display</a>
                        </li>
                        <li class="divider"></li>
                        {% if request.user.is_superuser %}
                          <li>
                            <a href="/admin" target="_blank">Admin Portal</a>
                          </li>
                        {% endif %}

                        {% if user.is_authenticated %}
                            <li><a href="{% url 'user:logout' %}">Log Out</a></li>
                        {% else %}
                            <li><a href="{% url 'user:login' %}">Sign In</a></li>
                        {% endif %}
                    </ul>
                </li>
              </ul>
            </div>
          </nav>
        </div>
    </div>
{% endblock %}


{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

{% block script %}
     {{ block.super }}
    <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'js/mapbox.js' %}"></script>
    <script src="{% static "js/plugins/iCheck/icheck.min.js" %}"></script>

    <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js'></script>
    <script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.3/leaflet.draw.js'></script>
    <script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
    <script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.2.0/leaflet-omnivore.min.js'></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-geodesy/v0.1.0/leaflet-geodesy.js'></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>

    <!-- Peity -->
    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>

    <!-- Peity -->
    <script src="{% static 'js/demo/peity-demo.js' %}"></script>
    <script src="{% static 'js/bootbox.min.js' %}"></script>
    <script src="{% static 'js/prospects_new_list.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/lead_list_custom.js' %}"></script>
    <!-- <script src="{% static 'js/custom_mapbox.js' %}"></script> -->
    <script src="{% static 'js/bootstrap-editable.min.js' %}"></script>
    <script src="{% static 'js/lead_update.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker_timepicker.min.js' %}"></script>
    <script src="{% static 'js/date_time.js' %}"></script>
{% endblock %}